# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRc3P7-MThYpxjnK7Iw9795FyKy-ePdm
"""

import pandas as pd

import pandas as pd

# Change the URL to point to the raw content of the CSV file on GitHub
# The raw URL is different from the URL displaying the file on GitHub
url = "https://raw.githubusercontent.com/Jujun8/sansan/main/data%20proyek.csv"
df = pd.read_csv(url)
df.head(16)

# Install dependencies (jika belum)
# !pip install scikit-learn pandas

import pandas as pd




# Load dataset
url = "https://raw.githubusercontent.com/Jujun8/sansan/main/data%20proyek.csv"
df = pd.read_csv(url)

# Cek nama kolom
print("Kolom tersedia:", df.columns)

# Pastikan kolom 'ulasan' dan 'skor' sesuai dengan dataset Anda
# Koreksi: Kolom 'content' adalah ulasan (teks), kolom 'score' adalah skor (target)
text_column = 'content'  # Ubah ini menjadi kolom teks
target_column = 'score' # Ubah ini menjadi kolom target

# Validasi kolom
if text_column not in df.columns or target_column not in df.columns:
    raise ValueError(f"Kolom '{text_column}' atau '{target_column}' tidak ditemukan dalam dataset.")

# Hapus baris kosong
df.dropna(subset=[text_column, target_column], inplace=True)

# Preprocessing
# Hanya lakukan lowercasing pada kolom teks
df[text_column] = df[text_column].astype(str).str.lower()
# Pastikan kolom target (skor) bertipe yang sesuai, misalnya int atau object untuk klasifikasi
df[target_column] = df[target_column].astype(str) # Ubah skor menjadi string jika MultinomialNB digunakan

# Pisahkan fitur dan target
X = df[text_column]
y = df[target_column]

# Split data training dan testing


# TF-IDF Vectorizer
# Gunakan stop_words='english' atau stop_words=None jika data non-Inggris dan tidak ada stop word list khusus


# N

# Evaluasi model

print("Laporan klasifikasi:")


# Prediksi ulasan baru
ulasan_baru = ["Barangnya bagus dan sesuai deskripsi."]



ulasan_baru2 = ["Produknya mengecewakan, tidak seperti yang diharapkan."]


