# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRc3P7-MThYpxjnK7Iw9795FyKy-ePdm
"""

import pandas as pd

import pandas as pd

# Change the URL to point to the raw content of the CSV file on GitHub
# The raw URL is different from the URL displaying the file on GitHub
url = "https://raw.githubusercontent.com/Jujun8/sansan/main/data%20proyek.csv"
df = pd.read_csv(url)
df.head(16)

text_column = 'userName' # Assuming 'userName' is the column containing text data
target_column = 'score'  # Assuming 'score' is the column containing the target score